apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  template:
    spec:
      containers:
      - name: hello-service
        image: nexus-registry-nexus.apps.cluster-lb3bc6.lb3bc6.example.opentlc.com/repository/docker/hello-dev/hello-service:prod-2022-08-26-17-35-05
