apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  template:
    spec:
      containers:
      - name: hello-service
        image: quay.senac.br/hello-dev/hello-service:prod-2023-04-26-15-13-32
