apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  template:
    spec:
      containers:
      - name: hello-service
        image: senac-registry-quay-openshift-operators.apps.cluster-c4csb.dynamic.opentlc.com/hello-spring-dev/hello-service:prd-2022-07-07-14-38-03
