apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  template:
    spec:
      containers:
      - name: hello-service
        image: nexus-registry-nexus.apps.cluster-lbaf40.lbaf40.example.opentlc.com/repository/docker/hello-dev/hello-service:7c8c9dd795feadc2ce4166a110e4a94c91a7d285
