apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  template:
    spec:
      containers:
      - name: hello-service
        image: example-nexusrepo-sonatype-nexus-service-nexus.apps.cluster-vcj6d.vcj6d.example.opentlc.com/hello-spring-dev/hello-service:prd-2022-07-07-14-38-03
