apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  template:
    spec:
      containers:
      - name: hello-service
        image: nexus-registry-2-nexus.apps.cluster-lb0eba.lb0eba.example.opentlc.com/hello-spring-dev/hello-service:prd-2022-07-07-14-38-03
