apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  template:
    spec:
      containers:
      - name: hello-service
        image: nexus-registry-nexus.apps.cluster-h2xgw.h2xgw.example.opentlc.com/repository/docker/hello-dev/hello-service:prod-2023-04-28-17-33-51
