apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  template:
    spec:
      containers:
      - name: hello-service
        image: nexus-registry-nexus.apps.cluster-lbaf40.lbaf40.example.opentlc.com/repository/docker/hello-dev/hello-service:prod-2023-04-26-14-59-37
