apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  template:
    spec:
      containers:
      - name: hello-service
        image: nexus-registry-nexus.apps.cluster-lbdc04.lbdc04.example.opentlc.com/repository/docker/hello-dev/hello-service:prod-2022-08-17-17-15-12
