apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  template:
    spec:
      containers:
      - name: hello-service
        image: nexus-registry-nexus.apps.cluster-tqkcs.tqkcs.sandbox944.opentlc.com/repository/docker/hello-dev/hello-service:dev-2022-08-16-15-54-11
        
