apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  template:
    spec:
      containers:
      - name: hello-service
        image: quay.senac.br/hello-dev/hello-service:dev-2022-08-16-15-54-11
